name: Fix Log Statements
on:
  push:
    branches:
      - main
  workflow_dispatch:  # دستی طور پر رن کرنے کا آپشن
jobs:
  fix-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install regex
      - name: Fix log statements in all .py files
        run: |
          find . -type f -name "*.py" -exec sed -i 's/log\.error(/logger.error(/g' {} \;
          find . -type f -name "*.py" -exec sed -i 's/log\.warning(/logger.warning(/g' {} \;
          find . -type f -name "*.py" -exec sed -i 's/log\.info(/logger.info(/g' {} \;
          find . -type f -name "*.py" -exec sed -i 's/log(/logger.error(/g' {} \;
          find . -type f -name "*.py" -exec grep -l "import logger" {} \; | xargs -I {} sh -c 'if ! grep -q "from utils.logger import logger" "{}"; then echo "from utils.logger import logger" | cat - "{}" > temp && mv temp "{}"; fi'
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Fixed log to logger in all .py files" || echo "No changes to commit"
          git push
